# Generated by Django 6.0.3 on 2026-03-11 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor', models.CharField(blank=True, max_length=255)),
                ('data', models.DateField(blank=True, null=True)),
                ('orgao', models.CharField(blank=True, max_length=255)),
                ('unidade_notificadora', models.CharField(blank=True, max_length=255)),
                ('motivo_violencia', models.CharField(blank=True, max_length=255)),
                ('lesao_autoprovocada', models.CharField(blank=True, max_length=50)),
                ('meio_agressao', models.CharField(blank=True, max_length=255)),
                ('multipla_ocorrencia', models.CharField(blank=True, max_length=50)),
                ('acompanhamento', models.CharField(blank=True, max_length=100)),
                ('local_acompanhamento', models.CharField(blank=True, max_length=255)),
                ('servico_inserido', models.CharField(blank=True, max_length=255)),
                ('situacao_ruptura_psr', models.CharField(blank=True, max_length=255)),
                ('outra_situacao', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Violacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violacoes', to='notificacoes.notificacao')),
            ],
        ),
        migrations.CreateModel(
            name='Violado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_social', models.CharField(blank=True, max_length=255)),
                ('nome_mae', models.CharField(blank=True, max_length=255)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('nis', models.CharField(blank=True, max_length=20)),
                ('cartao_sus', models.CharField(blank=True, max_length=30)),
                ('gestante', models.CharField(blank=True, max_length=30)),
                ('is_migrante', models.BooleanField(default=False)),
                ('nacionalidade', models.CharField(blank=True, max_length=100)),
                ('naturalidade', models.CharField(blank=True, max_length=100)),
                ('estado_civil', models.CharField(blank=True, max_length=100)),
                ('raca', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(blank=True, max_length=50)),
                ('segmento_lgbtqiapn', models.CharField(blank=True, max_length=100)),
                ('identidade_genero', models.CharField(blank=True, max_length=100)),
                ('is_pcd', models.BooleanField(default=False)),
                ('tipo_deficiencia', models.CharField(blank=True, max_length=100)),
                ('deficiencia', models.CharField(blank=True, max_length=100)),
                ('grau_instrucao', models.CharField(blank=True, max_length=100)),
                ('ciclo_vida', models.CharField(blank=True, max_length=100)),
                ('grupo_populacional', models.CharField(blank=True, max_length=255)),
                ('notificacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='violado', to='notificacoes.notificacao')),
            ],
        ),
        migrations.CreateModel(
            name='Violador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(blank=True, max_length=50)),
                ('raca_etnia', models.CharField(blank=True, max_length=100)),
                ('parentesco', models.CharField(blank=True, max_length=100)),
                ('ciclo_vida', models.CharField(blank=True, max_length=100)),
                ('susp_alcool_drogas', models.CharField(blank=True, max_length=50)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violadores', to='notificacoes.notificacao')),
            ],
        ),
    ]
