export const GRAU_INSTRUCAO_OPTIONS = [
  { label: "Não alfabetizado(a)", value: "NAO_ALFABETIZADO" },
  { label: "1ª a 4ª série incompleta do E. Fundamental", value: "FUNDAMENTAL_INCOMPLETO" },
  { label: "2ª a 4ª série completa do E. Fundamental", value: "FUNDAMENTAL_COMPLETO" },
  { label: "3ª a 8ª série incompleta do E. Fundamental", value: "FUNDAMENTAL_INCOMPLETO" },
  { label: "Ensino Fundamental Completo", value: "FUNDAMENTAL_COMPLETO" },
  { label: "Ensino Médio Incompleto", value: "MEDIO_INCOMPLETO" },
  { label: "Ensino Médio Completo", value: "MEDIO_COMPLETO" },
  { label: "Ensino Superior Incompleto", value: "SUPERIOR_INCOMPLETO" },
  { label: "Ensino Superior Completo", value: "SUPERIOR_COMPLETO" },
  { label: "Pós graduação (Especialização)", value: "POS_GRADUACAO" },
  { label: "Mestrado", value: "MESTRADO" },
  { label: "Doutorado", value: "DOUTORADO" },
  { label: "Ignorado", value: "IGNORADO" },
  { label: "Sem informação", value: "SEM_INFORMACAO" },
];
