export const PARENTESCO_VIOLADOR_OPTIONS = [
  { label: "O próprio sujeito", value: "PROPRIO_SUJEITO" },
  { label: "Pai / Mãe", value: "PAI_MAE" },
  { label: "Filho(a)", value: "FILHO" },
  { label: "Irmã(o)", value: "IRMAO" },
  { label: "Avô / Avó", value: "AVO" },
  { label: "Neto(a) ou Bisneto(a)", value: "NETO_BISNETO" },
  { label: "Tio(a)", value: "TIO" },
  { label: "Cônjuge / Companheiro", value: "CONJUGE_COMPANHEIRO" },
  { label: "Ex-cônjuge / Companheiro", value: "EX_CONJUGE_COMPANHEIRO" },
  { label: "Namorado(a)", value: "NAMORADO" },
  { label: "Ex-Namorado(a)", value: "EX_NAMORADO" },
  { label: "Padrasto / Madrasta", value: "PADRASTO_MADRASTA" },
  { label: "Enteado(a)", value: "ENTEADO" },
  { label: "Cuidador", value: "CUIDADOR" },
  { label: "Sem parentesco", value: "SEM_PARENTESCO" },
  { label: "Estado - Órgão Público", value: "ESTADO_ORGAO_PUBLICO" },
  { label: "Outro", value: "OUTRO" },
  { label: "Sem informação", value: "SEM_INFORMACAO" },
] as const;
